package com.ecom.product.models;

import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Data;


@Data
@Document(collection = "products")
public class Product {

    @Id
    private String id;
    private String name;
    private String description;
    private String category;
    private double price;
    private int quantity;
    private List<String> images;

    // Constructors, getters, and setters can be generated by Lombok's @Data annotation
}
